# Generated by Django 4.1.5 on 2023-01-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_id_liquidacion', '0002_alter_idliquidacion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=2)),
                ('legajo', models.PositiveIntegerField()),
                ('beneficiario', models.CharField(max_length=25)),
                ('tipo_pension', models.PositiveIntegerField()),
                ('codigo', models.PositiveIntegerField()),
                ('codigo_descripcion', models.CharField(max_length=25)),
                ('codigo_tipo', models.CharField(max_length=1)),
                ('importe', models.FloatField()),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_id_liquidacion.idliquidacion')),
            ],
            options={
                'ordering': ['-liquidacion', 'localidad', 'legajo', 'codigo'],
            },
        ),
    ]
