# Generated by Django 4.1.5 on 2023-01-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_detalle_liquidacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleliquidacion',
            name='recibo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalleliquidacion',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
