# Generated by Django 4.1.5 on 2023-04-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_detalle_liquidacion', '0003_detalleliquidacion_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleliquidacion',
            name='documento',
            field=models.PositiveIntegerField(),
        ),
    ]
