# Generated by Django 4.1.5 on 2023-07-20 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ubicacion', '0004_alter_ubicacion_options_and_more'),
        ('app_detalle_liquidacion', '0004_alter_detalleliquidacion_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleliquidacion',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_ubicacion.ubicacion'),
        ),
    ]
