# Generated by Django 4.1.5 on 2023-07-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_detalle_liquidacion', '0005_alter_detalleliquidacion_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleliquidacion',
            name='cuil',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
