# Generated by Django 4.1.5 on 2023-07-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_detalle_liquidacion', '0006_detalleliquidacion_cuil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleliquidacion',
            name='codigo_tipo',
            field=models.CharField(max_length=25),
        ),
    ]
