# Generated by Django 4.1.5 on 2023-01-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='beneficiario',
            constraint=models.UniqueConstraint(fields=('ubicacion', 'legajo'), name='legajo_unico'),
        ),
    ]
