# Generated by Django 4.1.5 on 2023-04-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_beneficiarios', '0002_beneficiario_legajo_unico'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='creado_usuario',
            field=models.CharField(default='ADMIN', max_length=30),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='modificado_usuario',
            field=models.CharField(default='ADMIN', max_length=30),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='tipo_doc',
            field=models.CharField(choices=[('3', 'DNI'), ('0', 'OTRO')], default='3', max_length=1),
        ),
    ]
