# Generated by Django 4.1.5 on 2023-04-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_beneficiarios', '0003_beneficiario_creado_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiario',
            old_name='tipo_doc',
            new_name='documento_tipo',
        ),
    ]
