# Generated by Django 4.1.5 on 2023-04-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tipo_pensiones', '0002_alter_tipopension_descripcion'),
        ('app_ubicacion', '0002_alter_ubicacion_localidad'),
        ('app_beneficiarios', '0005_alter_beneficiario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='imagen',
            field=models.ImageField(default='user_generic.html', upload_to='beneficiarios/img'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='tipo_pension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_tipo_pensiones.tipopension'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_ubicacion.ubicacion'),
        ),
    ]
