# Generated by Django 4.1.5 on 2023-04-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_beneficiarios', '0006_beneficiario_imagen_alter_beneficiario_tipo_pension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='imagen',
            field=models.ImageField(default='user_generic.png', upload_to='beneficiarios/img'),
        ),
    ]
