# Generated by Django 4.1.5 on 2023-07-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_beneficiarios', '0008_beneficiario_cuil_beneficiario_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='direccion',
            field=models.CharField(default='SIN INFORMACIÓN DISPONIBLE', max_length=40),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No Binario'), ('N', 'No Declarado')], default='N', max_length=1),
        ),
    ]
