# Generated by Django 4.1.5 on 2023-08-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_beneficiarios', '0010_alter_beneficiario_creado_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
