# Generated by Django 4.1.5 on 2023-08-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_beneficiarios', '0011_beneficiario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='tipo_carga',
            field=models.CharField(choices=[('U', 'Carga Manual'), ('M', 'Carga Masiva desde Archivo'), ('A', 'Carga a través de API')], default='U', max_length=1),
        ),
    ]
