# Generated by Django 4.1.5 on 2023-08-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_beneficiarios', '0012_beneficiario_tipo_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='documento_tipo',
            field=models.CharField(choices=[('03', 'DNI'), ('00', 'OTRO')], default='03', max_length=2),
        ),
    ]
