# Generated by Django 4.1.5 on 2023-04-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tipo_pensiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopension',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
