# Generated by Django 4.1.5 on 2023-06-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tipo_pensiones', '0002_alter_tipopension_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopension',
            name='codigo_numerico',
            field=models.PositiveIntegerField(unique=True, verbose_name='Código Numérico'),
        ),
        migrations.AlterField(
            model_name='tipopension',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción detallada'),
        ),
        migrations.AlterField(
            model_name='tipopension',
            name='descripcion_corta',
            field=models.CharField(max_length=4, verbose_name='Descripción corta'),
        ),
    ]
