# Generated by Django 4.1.5 on 2023-08-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tipo_pensiones', '0004_alter_tipopension_descripcion_corta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipopension',
            options={'ordering': ['codigo_numerico', 'descripcion_corta']},
        ),
    ]
