# Generated by Django 4.1.5 on 2023-08-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tipo_pensiones', '0005_alter_tipopension_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopension',
            name='creado_usuario',
            field=models.CharField(default='---', max_length=30),
        ),
        migrations.AddField(
            model_name='tipopension',
            name='modificado_usuario',
            field=models.CharField(default='---', max_length=30),
        ),
        migrations.AddField(
            model_name='tipopension',
            name='tipo_carga',
            field=models.CharField(choices=[('U', 'Carga Manual'), ('M', 'Carga Masiva desde Archivo'), ('A', 'Carga a través de API')], default='U', max_length=1),
        ),
    ]
