# Generated by Django 4.1.5 on 2023-01-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_tipo_pensiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_numerico', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=25)),
                ('tipo', models.CharField(choices=[('R', 'Remunerativo'), ('N', 'No Remunerativo'), ('D', 'Descuento')], max_length=1)),
                ('calculo', models.CharField(choices=[('P', 'Porcentaje sobre Remunerativo'), ('T', 'Porcentaje robre total'), ('F', 'Valor Fijo')], max_length=1)),
                ('valor', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('pension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tipo_pensiones.tipopension')),
            ],
        ),
    ]
