# Generated by Django 4.1.5 on 2023-01-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_codigos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='calculo',
            field=models.CharField(choices=[('P', 'Porcentaje sobre Remunerativo'), ('T', 'Porcentaje sobre Total Pago'), ('F', 'Valor Fijo')], max_length=1),
        ),
    ]
