# Generated by Django 4.1.5 on 2023-01-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_codigos', '0003_alter_codigo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='tipo',
            field=models.CharField(choices=[('R', 'Remunerativo'), ('N', 'No Remunerativo'), ('D', 'Descuento'), ('X', 'Redondeo Remuneraciones'), ('Y', 'Redondeo Deducciones')], max_length=1),
        ),
    ]
