# Generated by Django 4.1.5 on 2023-06-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tipo_pensiones', '0003_alter_tipopension_codigo_numerico_and_more'),
        ('app_codigos', '0005_codigo_modificado_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='calculo',
            field=models.CharField(choices=[('P', 'Porcentaje sobre Remunerativo'), ('T', 'Porcentaje sobre Total Pago'), ('F', 'Valor Fijo')], max_length=1, verbose_name='Base de Cálculo'),
        ),
        migrations.AlterField(
            model_name='codigo',
            name='codigo_numerico',
            field=models.PositiveIntegerField(verbose_name='Código Numérico'),
        ),
        migrations.AlterField(
            model_name='codigo',
            name='descripcion',
            field=models.CharField(max_length=25, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='codigo',
            name='pension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tipo_pensiones.tipopension', verbose_name='Aplica al Tipo de Pensión'),
        ),
        migrations.AlterField(
            model_name='codigo',
            name='tipo',
            field=models.CharField(choices=[('R', 'Remunerativo'), ('N', 'No Remunerativo'), ('D', 'Descuento'), ('X', 'Redondeo Remuneraciones'), ('Y', 'Redondeo Deducciones')], max_length=1, verbose_name='Tipo de Concepto'),
        ),
    ]
