# Generated by Django 4.1.5 on 2023-08-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_codigos', '0007_codigo_signo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigo',
            options={'ordering': ['pension', 'codigo_numerico', 'activo']},
        ),
        migrations.AddField(
            model_name='codigo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
