# Generated by Django 4.1.5 on 2023-08-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_codigos', '0008_alter_codigo_options_codigo_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigo',
            name='observaciones',
        ),
    ]
