# Generated by Django 4.1.5 on 2023-01-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='localidad',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
