# Generated by Django 4.1.5 on 2023-01-27 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_id_liquidacion', '0002_alter_idliquidacion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='idliquidacion',
            name='fecha_pago',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 1, 27, 17, 21, 42, 967755, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
