# Generated by Django 4.1.5 on 2023-04-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_id_liquidacion', '0004_alter_idliquidacion_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idliquidacion',
            name='anio',
            field=models.PositiveIntegerField(verbose_name='año'),
        ),
        migrations.AlterField(
            model_name='idliquidacion',
            name='mes',
            field=models.CharField(choices=[('01ENE', 'ENERO'), ('02FEB', 'FEBRERO'), ('03MRZ', 'MARZO'), ('04ABR', 'ABRIL'), ('05MAY', 'MAYO'), ('06JUN', 'JUNIO'), ('07JUL', 'JULIO'), ('08AGO', 'AGOSTO'), ('09SEP', 'SEPTIEMBRE'), ('10OCT', 'OCTUBRE'), ('11NOV', 'NOVIEMBRE'), ('12DIC', 'DICIEMBRE'), ('13SC1', 'SAC PRIMERA CUOTA'), ('14SC2', 'SAC SEGUNDA CUOTA')], max_length=5, verbose_name='período'),
        ),
    ]
