# Generated by Django 4.1.5 on 2023-07-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_id_liquidacion', '0005_alter_idliquidacion_anio_alter_idliquidacion_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='idliquidacion',
            name='fecha_ultima_ejecucion',
            field=models.DateTimeField(null=True),
        ),
    ]
