# Generated by Django 4.1.5 on 2023-04-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_codigos', '0005_codigo_modificado_usuario'),
        ('app_beneficiarios', '0006_beneficiario_imagen_alter_beneficiario_tipo_pension_and_more'),
        ('app_movimiento_mensual', '0002_alter_movimientomensual_importe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientomensual',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_beneficiarios.beneficiario'),
        ),
        migrations.AlterField(
            model_name='movimientomensual',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_codigos.codigo'),
        ),
    ]
