# Generated by Django 4.1.5 on 2023-04-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movimiento_mensual', '0003_alter_movimientomensual_beneficiario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientomensual',
            name='pendiente',
            field=models.BooleanField(default=False),
        ),
    ]
