# Generated by Django 4.1.5 on 2023-04-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_movimiento_mensual', '0006_alter_movimientomensual_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientomensual',
            options={'ordering': ['-modificado', 'id_liquidacion', 'beneficiario']},
        ),
    ]
