# Generated by Django 4.1.5 on 2023-08-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movimiento_mensual', '0008_movimientomensual_creado_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientomensual',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
