# Generated by Django 4.1.5 on 2023-08-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movimiento_mensual', '0009_movimientomensual_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientomensual',
            name='tipo_carga',
            field=models.CharField(choices=[('U', 'Carga Manual'), ('M', 'Carga Masiva desde Archivo'), ('A', 'Carga a través de API')], default='M', max_length=1),
        ),
    ]
